from dotenv import load_dotenv
import os

load_dotenv()

SUPABASE_URL = os.getenv("https://tsruvplxeloculjwhpmb.supabase.co")
SUPABASE_KEY = os.getenv("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcnV2cGx4ZWxvY3VsandocG1iIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NTY1OTY2NCwiZXhwIjoyMDYxMjM1NjY0fQ.nubppa8TmDxSaxW7j1Wj96au0S-fZ5hGaOX8uJHt-m0")