from dotenv import load_dotenv
import os

load_dotenv()

SUPABASE_URL = os.getenv("https://tsruvplxeloculjwhpmb.supabase.co")
SUPABASE_KEY = os.getenv("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcnV2cGx4ZWxvY3VsandocG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTk2NjQsImV4cCI6MjA2MTIzNTY2NH0.gfvqota3DYSb6CxzXyIZmfvO7bminWjNjDSJTWW0ftk")